name: publish 

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: grafana/k6build

jobs:

  publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392  # v3.6.0
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          version: v0.9.1
          cache-binary: false
      - name: Log into ghcr.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
             IMAGE_VERSION=$GITHUB_REF_NAME
          else
             IMAGE_VERSION='latest'
          fi
          IMAGE_TAG="$REGISTRY/$IMAGE_NAME:${IMAGE_VERSION}"
          docker buildx build -t $IMAGE_TAG --platform=linux/amd64,linux/arm64 --push .
